/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HouseRouteRouteImport } from './routes/$house/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HouseIndexRouteImport } from './routes/$house/index'
import { Route as HouseCharacterCharacterIdRouteImport } from './routes/$house/character/$characterId'

const HouseRouteRoute = HouseRouteRouteImport.update({
  id: '/$house',
  path: '/$house',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseIndexRoute = HouseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HouseRouteRoute,
} as any)
const HouseCharacterCharacterIdRoute =
  HouseCharacterCharacterIdRouteImport.update({
    id: '/character/$characterId',
    path: '/character/$characterId',
    getParentRoute: () => HouseRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$house': typeof HouseRouteRouteWithChildren
  '/$house/': typeof HouseIndexRoute
  '/$house/character/$characterId': typeof HouseCharacterCharacterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$house': typeof HouseIndexRoute
  '/$house/character/$characterId': typeof HouseCharacterCharacterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$house': typeof HouseRouteRouteWithChildren
  '/$house/': typeof HouseIndexRoute
  '/$house/character/$characterId': typeof HouseCharacterCharacterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$house' | '/$house/' | '/$house/character/$characterId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$house' | '/$house/character/$characterId'
  id:
    | '__root__'
    | '/'
    | '/$house'
    | '/$house/'
    | '/$house/character/$characterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HouseRouteRoute: typeof HouseRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$house': {
      id: '/$house'
      path: '/$house'
      fullPath: '/$house'
      preLoaderRoute: typeof HouseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$house/': {
      id: '/$house/'
      path: '/'
      fullPath: '/$house/'
      preLoaderRoute: typeof HouseIndexRouteImport
      parentRoute: typeof HouseRouteRoute
    }
    '/$house/character/$characterId': {
      id: '/$house/character/$characterId'
      path: '/character/$characterId'
      fullPath: '/$house/character/$characterId'
      preLoaderRoute: typeof HouseCharacterCharacterIdRouteImport
      parentRoute: typeof HouseRouteRoute
    }
  }
}

interface HouseRouteRouteChildren {
  HouseIndexRoute: typeof HouseIndexRoute
  HouseCharacterCharacterIdRoute: typeof HouseCharacterCharacterIdRoute
}

const HouseRouteRouteChildren: HouseRouteRouteChildren = {
  HouseIndexRoute: HouseIndexRoute,
  HouseCharacterCharacterIdRoute: HouseCharacterCharacterIdRoute,
}

const HouseRouteRouteWithChildren = HouseRouteRoute._addFileChildren(
  HouseRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HouseRouteRoute: HouseRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
